#!/bin/bash
# This script was generated by BRB-SeqTools 1.2 (Oct 2017). BRB-SeqTools does not take the responsibility for any damage, loss of data resulting from the use of the software.

set -e
export seqtools_samtools_PATH=/opt/SeqTools/bin/samtools-1.4:/opt/SeqTools/bin/samtools-1.4/misc
export PATH=$seqtools_samtools_PATH:$PATH
export seqtools_subread_PATH=/opt/SeqTools/bin/subread-1.5.2-source/bin
export PATH=$seqtools_subread_PATH:$PATH

export seqtools_bcftools_PATH=/opt/SeqTools/bin/bcftools-1.4
export PATH=$seqtools_bcftools_PATH:$PATH

outputDir="/home/brb/Downloads/testdata/GSE11209/output_subread"
if [ -f "$outputDir"/BugReport.tar.gz ]; then rm "$outputDir"/BugReport.tar.gz; fi;
if ls "$outputDir"/*.count &> /dev/null; then rm "$outputDir"/*.count ; fi
if ls "$outputDir"/*.vcf &> /dev/null; then rm "$outputDir"/*.vcf ; fi
if ls "$outputDir"/*.idx &> /dev/null; then rm "$outputDir"/*.idx ; fi
if [ -d "$outputDir/tmp" ]; then rm -r -f "$outputDir/tmp"; fi

if [ ! -d "$outputDir/tmp" ]; then mkdir "$outputDir/tmp"; fi

if [ -f "$outputDir/tmp/log.txt" ]; then rm "$outputDir/tmp/log.txt"; fi
touch "$outputDir/tmp/log.txt"

echo bowtie: /opt/SeqTools/bin/bowtie2-2.2.9 >> "$outputDir/tmp/log.txt"
echo tophat: /opt/SeqTools/bin/tophat-2.1.1.Linux_x86_64 >> "$outputDir/tmp/log.txt"
echo samtools: /opt/SeqTools/bin/samtools-1.4 >> "$outputDir/tmp/log.txt"
echo HTSeq: `python -c "import HTSeq; print HTSeq.__version__"` >> "$outputDir/tmp/log.txt"

runDGE=true
runVC=true
rerunAligner=true
cleanUp=false

cd "/home/brb/Downloads/testdata/GSE11209"

# dT_ori 
echo dT_ori `date +'%Y-%m-%d %T'` >> "$outputDir/tmp/log.txt"
echo "dT_ori (1/2)"
if [ ! -f dT_ori/accepted_hits_subjunc.bam ] || ([ -f dT_ori/accepted_hits_subjunc.bam ] && [ $rerunAligner == "true" ]) ; then
    if [ ! -d "Subreadindex" ]; then mkdir "Subreadindex"; fi
    echo "    (`date +'%Y-%m-%d %T'`) creating Subread index" | tee -a "$outputDir/tmp/log.txt"
    (subread-buildindex -o Subreadindex/Subreadindex /home/brb/Downloads/testdata/Saccharomyces_cerevisiae/Ensembl/EF4/Sequence/WholeGenomeFasta/genome.fa ) >> "$outputDir/tmp/log.txt" 2>&1
    if [ ! -d "dT_ori" ]; then mkdir "dT_ori"; fi
        echo "    (`date +'%Y-%m-%d %T'`) running read alignment" | tee -a "$outputDir/tmp/log.txt"
        (subjunc -T 11  -i Subreadindex/Subreadindex -r SRR002051.fastq -o dT_ori/accepted_hits_subjunc.bam) >> "$outputDir/tmp/log.txt" 2>&1
    fi;
if [ $runDGE == "true" ]; then
    cd "dT_ori"
    echo "    (`date +'%Y-%m-%d %T'`) creating count file" | tee -a "$outputDir/tmp/log.txt"
    (featureCounts -T 11  -a /home/brb/Downloads/testdata/Saccharomyces_cerevisiae/Ensembl/EF4/Annotation/Genes/genes.gtf -o /home/brb/Downloads/testdata/GSE11209/output_subread/dT_ori.count accepted_hits_subjunc.bam > "/home/brb/Downloads/testdata/GSE11209/output_subread/.count") >> "$outputDir/tmp/log.txt" 2>&1
    if ls "$outputDir"/*.count.summary &> /dev/null; then rm "$outputDir"/*.count.summary ; fi
    if ls "$outputDir"/.count &> /dev/null; then rm "$outputDir"/.count ; fi
    if [ $cleanUp == "true" ]; then
        rm -rf `ls | grep -v 'accepted_hits_tophat.bam' | grep -v 'accepted_hits_star.bam' | grep -v 'accepted_hits_bwa.bam' | grep -v 'accepted_hits_usr.bam' | grep -v 'accepted_hits_subread.bam'| grep -v 'accepted_hits_subjunc.bam' | grep -v 'align_summary.txt' | grep -v 'Log.final.out' `
    fi;
    cd ..
fi

if [ $runVC == "true" ]; then
    # SortAndIndexBam. Input: accepted_hits.bam. Output: sorted.bam
    cd "dT_ori"
    echo "    (`date +'%Y-%m-%d %T'`) sorting bam file" >> "$outputDir/tmp/log.txt"

    (samtools sort -@ 11 accepted_hits_subjunc.bam -o sorted.bam) >> "$outputDir/tmp/log.txt" 2>&1
    echo "    (`date +'%Y-%m-%d %T'`) indexing bam file" >> "$outputDir/tmp/log.txt"

    (samtools index sorted.bam) >> "$outputDir/tmp/log.txt" 2>&1
    # MarkDuplication (optional). Input: sort.bam. Output: Libraryname.bam
    echo "    (`date +'%Y-%m-%d %T'`) marking duplicates" | tee -a "$outputDir/tmp/log.txt"
    (java -Xmx10g -jar /opt/SeqTools/bin/picard-tools-2.1.1/picard.jar  MarkDuplicates METRICS_FILE=MarkDudup.metrics INPUT=sorted.bam OUTPUT=dT_ori.bam) >> "$outputDir/tmp/log.txt" 2>&1
    # SamtoolCallVariant. Input: LibraryName.bam. Output: LibraryName_raw.vcf
    echo "    (`date +'%Y-%m-%d %T'`) calling variants" | tee -a "$outputDir/tmp/log.txt"
    (samtools mpileup -uf "/home/brb/Downloads/testdata/Saccharomyces_cerevisiae/Ensembl/EF4/Sequence/WholeGenomeFasta/genome.fa" dT_ori.bam | \
          bcftools call -vmO v -o "/home/brb/Downloads/testdata/GSE11209/output_subread/dT_ori_raw.vcf") >> "$outputDir/tmp/log.txt" 2>&1
    if [ $cleanUp == "true" ]; then
        rm -rf `ls | grep -v 'accepted_hits_tophat.bam' | grep -v 'accepted_hits_star.bam' | grep -v 'accepted_hits_bwa.bam' | grep -v 'accepted_hits_subread.bam' | grep -v 'accepted_hits_subjunc.bam' | grep -v 'accepted_hits_usr.bam'  | grep -v 'align_summary.txt'`
    fi;
    cd ..
    echo "    (`date +'%Y-%m-%d %T'`) finish variant call" | tee -a "$outputDir/tmp/log.txt"
    # echo "    dT_ori_raw.vcf" is created | tee -a "$outputDir/tmp/log.txt"
fi

# RH_ori 
echo RH_ori `date +'%Y-%m-%d %T'` >> "$outputDir/tmp/log.txt"
echo "RH_ori (2/2)"
if [ ! -f RH_ori/accepted_hits_subjunc.bam ] || ([ -f RH_ori/accepted_hits_subjunc.bam ] && [ $rerunAligner == "true" ]) ; then
    if [ ! -d "RH_ori" ]; then mkdir "RH_ori"; fi
        echo "    (`date +'%Y-%m-%d %T'`) running read alignment" | tee -a "$outputDir/tmp/log.txt"
        (subjunc -T 11  -i Subreadindex/Subreadindex -r SRR002059.fastq -o RH_ori/accepted_hits_subjunc.bam) >> "$outputDir/tmp/log.txt" 2>&1
    fi;
if [ $runDGE == "true" ]; then
    cd "RH_ori"
    echo "    (`date +'%Y-%m-%d %T'`) creating count file" | tee -a "$outputDir/tmp/log.txt"
    (featureCounts -T 11  -a /home/brb/Downloads/testdata/Saccharomyces_cerevisiae/Ensembl/EF4/Annotation/Genes/genes.gtf -o /home/brb/Downloads/testdata/GSE11209/output_subread/RH_ori.count accepted_hits_subjunc.bam > "/home/brb/Downloads/testdata/GSE11209/output_subread/.count") >> "$outputDir/tmp/log.txt" 2>&1
    if ls "$outputDir"/*.count.summary &> /dev/null; then rm "$outputDir"/*.count.summary ; fi
    if ls "$outputDir"/.count &> /dev/null; then rm "$outputDir"/.count ; fi
    if [ $cleanUp == "true" ]; then
        rm -rf `ls | grep -v 'accepted_hits_tophat.bam' | grep -v 'accepted_hits_star.bam' | grep -v 'accepted_hits_bwa.bam' | grep -v 'accepted_hits_usr.bam' | grep -v 'accepted_hits_subread.bam'| grep -v 'accepted_hits_subjunc.bam' | grep -v 'align_summary.txt' | grep -v 'Log.final.out' `
    fi;
    cd ..
fi

if [ $runVC == "true" ]; then
    # SortAndIndexBam. Input: accepted_hits.bam. Output: sorted.bam
    cd "RH_ori"
    echo "    (`date +'%Y-%m-%d %T'`) sorting bam file" >> "$outputDir/tmp/log.txt"

    (samtools sort -@ 11 accepted_hits_subjunc.bam -o sorted.bam) >> "$outputDir/tmp/log.txt" 2>&1
    echo "    (`date +'%Y-%m-%d %T'`) indexing bam file" >> "$outputDir/tmp/log.txt"

    (samtools index sorted.bam) >> "$outputDir/tmp/log.txt" 2>&1
    # MarkDuplication (optional). Input: sort.bam. Output: Libraryname.bam
    echo "    (`date +'%Y-%m-%d %T'`) marking duplicates" | tee -a "$outputDir/tmp/log.txt"
    (java -Xmx10g -jar /opt/SeqTools/bin/picard-tools-2.1.1/picard.jar  MarkDuplicates METRICS_FILE=MarkDudup.metrics INPUT=sorted.bam OUTPUT=RH_ori.bam) >> "$outputDir/tmp/log.txt" 2>&1
    # SamtoolCallVariant. Input: LibraryName.bam. Output: LibraryName_raw.vcf
    echo "    (`date +'%Y-%m-%d %T'`) calling variants" | tee -a "$outputDir/tmp/log.txt"
    (samtools mpileup -uf "/home/brb/Downloads/testdata/Saccharomyces_cerevisiae/Ensembl/EF4/Sequence/WholeGenomeFasta/genome.fa" RH_ori.bam | \
          bcftools call -vmO v -o "/home/brb/Downloads/testdata/GSE11209/output_subread/RH_ori_raw.vcf") >> "$outputDir/tmp/log.txt" 2>&1
    if [ $cleanUp == "true" ]; then
        rm -rf `ls | grep -v 'accepted_hits_tophat.bam' | grep -v 'accepted_hits_star.bam' | grep -v 'accepted_hits_bwa.bam' | grep -v 'accepted_hits_subread.bam' | grep -v 'accepted_hits_subjunc.bam' | grep -v 'accepted_hits_usr.bam'  | grep -v 'align_summary.txt'`
    fi;
    cd ..
    echo "    (`date +'%Y-%m-%d %T'`) finish variant call" | tee -a "$outputDir/tmp/log.txt"
    # echo "    RH_ori_raw.vcf" is created | tee -a "$outputDir/tmp/log.txt"
fi

echo completed `date +'%Y-%m-%d %T'` >> "$outputDir/tmp/log.txt"
